### ISSUE TITLE
Error in W3bstream "ABORT: invalid downcast

### ISSUE THREAD

**Issue by simonerom** [machinefi/w3bstream-wasm-assemblyscript-sdk#1]
This is what I have in my start() function:
```ts
29: export function start(rid: i32): i32 {
30:  Log("start function called");
31:  let payloadStr = GetDataByRID(rid);
32:  Log("payload: " + payloadStr);
33:  const TokenContractAddress = GetEnv("TokenContractAddress");
34:  Log("TokenContractAddress: " + TokenContractAddress);
35:  let payload: JSON.Obj = JSON.parse(payloadStr) as JSON.Obj;
36:  let data: JSON.Obj = payload.getObj("data") as JSON.Obj;
37:  const measurement: JSON.Integer | null = data.getInteger("sensor_reading");
38:  const timestamp: JSON.Str | null = data.getString("timestamp");
39:  return 0;
40: }
```

When I trigger the function in W3bstream, I get this error:  `"ABORT: invalid downcast at assembly/index.ts:35:27"`
```json
{"@app":"app_01","@lv":"info","@prj":"srv-applet-mgr","@src":"wasm","@ts":"20230220-235502.382Z","msg":"start function called"}
{"@app":"app_01","@lv":"info","@prj":"srv-applet-mgr","@src":"wasm","@ts":"20230220-235502.383Z","msg":"payload: \"payload\": {\n    \"data\": {\n      \"sensor_reading\": 3.97,\n      \"timestamp\": 1676935652\n    },\n    \"signature\": \"000000004065...aa017cb8ec7\",\n    \"public_key\": \"04bb9e40...833ae82aa425539\"\n  }"}
{"@app":"app_01","@lv":"info","@prj":"srv-applet-mgr","@src":"wasm","@ts":"20230220-235502.384Z","msg":"TokenContractAddress: 0x8193C99778e1759f5976b9d23BBE062ab7AE66f6"}
{"@app":"app_01","@lv":"info","@prj":"srv-applet-mgr","@src":"wasm","@ts":"20230220-235502.385Z","msg":"ABORT: invalid downcast at assembly/index.ts:35:27"}
{"@lv":"error","@prj":"srv-applet-mgr","@ts":"20230220-235502.388Z","msg":"wasm trap: wasm `unreachable` instruction executed\nwasm backtrace:\n    0: 0x55a6 - \u003cunknown\u003e!\u003cwasm function 70\u003e\n"}
{"@agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15","@cst":32,"@lv":"info","@mtd":"POS","@prj":"srv-applet-mgr","@rmt":"192.168.32.6","@status":201,"@tag":"access","@ts":"20230220-235502.390Z","@url":"/srv-applet-mgr/v0/event/EnergyMeter","msg":""}
```

**Comment by simonerom** [comment]
it seems it's due to the fact that now, in W3bstream 1.0, the payload must be an array of objects. If I send the payload like 
```   
 "payload": {
      "data": {
        "sensor_reading": 3.97,
        "timestamp": 1676935652
      },
      "signature": "000000004065...aa017cb8ec7",
      "public_key": "04bb9e40...833ae82aa425539"
    }
```
it's not interpreted correctly inside the WASM: even in this case, the payload should be sent as `[ { "payload": { ... } } ]` 


We may want to have a check in W3bstream here and emit an error about the format of the payload @Liuhaai .

**Comment by simonerom** [comment]
I also suspect that this may be an issue with the send event dialog in W3bstream-Studio, which sends the wrong payload format under some conditions that may also be related to the incorrect code formatting. @uu-z may want to dig deeper
